language: haskell
before_install:
  - "sudo apt-get install libpcre3 libpcre3-dev"
  - "cabal install --force-reinstalls" # register library as a package (needs to be fully installed on the system before the tests are run)
after_script:
  - "cat dist/test/aeson-schema-*-tests.log"