language: haskell
before_script:
  - "cabal install test-framework test-framework-hunit HUnit test-framework-quickcheck2-0.2.12.2 QuickCheck"
after_script:
  - "cat dist/test/aeson-schema-*-tests.log"