language: haskell
ghc:
  - 7.6
  - 7.8
before_install:
  - "sudo apt-get install libpcre3 libpcre3-dev"
  - "cabal install --force-reinstalls --enable-tests" # register library as a package (needs to be fully installed on the system before the tests are run)
after_script:
  - "cat dist/test/aeson-schema-*-tests.log"